Repository frontend-park-mail-ru/2021_2_LadnoDavayteBezRoflov, pull requests merged in 2021-11, with the labels that each got.

#24 LDBR-2.4: Добавить страницу настроек профиля
  public/assets/icons/upload.webp
  src/actions/boards.js
  src/actions/settings.js
  src/actions/user.js
  src/components/Footer/Footer.hbs
  src/components/Navbar/Navbar.hbs
  src/components/Navbar/Navbar.js
  src/constants/constants.js
  src/index.js
  src/index_template.html
  src/modules/Network/Network.js
  src/modules/Validator/Validator.js
  src/stores/BaseStore.js
  src/stores/BoardsStore/BoardsStore.js
  src/stores/SettingsStore/SettingsStore.js
  src/stores/UserStore/UserStore.js
  src/views/ProfileView/ProfileView.hbs
  src/views/ProfileView/ProfileView.js
  src/views/ProfileView/ProfileView.scss
  src/views/RegisterView/RegisterView.js
Labels: требуется ревью менторов

#26 LDBR 2.15: Создание доски
  src/actions/boards.js
  src/constants/constants.js
  src/index_template.html
  src/modules/Network/Network.js
  src/modules/Validator/Validator.js
  src/stores/BoardsStore/BoardsStore.js
  src/styles/scss/Common.scss
  src/styles/scss/Constants.scss
  src/styles/scss/Fonts.scss
  src/styles/scss/Reset.scss
  src/views/BoardsView/BoardsView.hbs
  src/views/BoardsView/BoardsView.js
  src/views/BoardsView/BoardsView.scss
  src/views/BoardsView/IsEqualHelper.js
  src/views/LoginView/LoginView.scss
  src/views/RegisterView/RegisterView.hbs
  src/views/RegisterView/RegisterView.js
  src/views/RegisterView/RegisterView.scss
Labels: требуется ревью менторов

#29 LDBR-2.26: CardList, BoardSetting
  package-lock.json
  package.json
  server/server.js
  src/actions/board.js
  src/actions/boards.js
  src/actions/cardlist.js
  src/components/BaseComponent.js
  src/components/Card/Card.js
  src/components/CardList/CardList.hbs
  src/components/CardList/CardList.js
  src/components/CardList/CardList.scss
  src/components/CardList/CardListPopup.hbs
  src/components/Footer/Footer.js
  src/components/Navbar/Navbar.js
  src/constants/constants.js
  src/index.js
  src/index_template.html
  src/modules/Helpers/IsEqualHelper.js
  src/modules/Network/Network.js
  src/modules/Validator/Validator.js
  src/popups/BoardSetting/BoardSettingPopUp.hbs
  src/popups/BoardSetting/BoardSettingPopUp.js
  src/popups/BoardSetting/BoardSettingPopUp.scss
  src/popups/CardList/CardListPopUp.hbs
  src/popups/CardList/CardListPopUp.js
  src/popups/CreateBoard/CreateBoardPopUp.hbs
  src/popups/CreateBoard/CreateBoardPopUp.js
  src/popups/DeleteCardList/DeleteCardListPopUp.hbs
  src/popups/DeleteCardList/DeleteCardListPopUp.js
  src/stores/BoardStore/BoardStore.js
  src/stores/BoardsStore/BoardsStore.js
  src/styles/scss/Common.scss
  src/styles/scss/Constants.scss
  src/styles/scss/PopUp.scss
  src/views/BaseView.js
  src/views/BoardView/BoardView.hbs
  src/views/BoardView/BoardView.js
  src/views/BoardView/board.scss
  src/views/BoardView/card.scss
  src/views/BoardsView/BoardsView.hbs
  src/views/BoardsView/BoardsView.js
  src/views/BoardsView/BoardsView.scss
  src/views/LoginView/LoginView.js
  src/views/ProfileView/ProfileView.js
  src/views/RegisterView/RegisterView.js
  webpack.config.js
Labels: требуется ревью менторов

#28 LBDR 2.29: Вынести общий функционал в Base Component
  src/components/BaseComponent.js
  src/components/Footer/Footer.js
  src/components/Navbar/Navbar.js
  src/stores/BoardStore/BoardStore.js
Labels: требуется ревью менторов

#30 LDBR-2.27: Исправить карточки
  src/actions/card.js
  src/components/Card/Card.hbs
  src/components/Card/Card.js
  src/components/Card/CardPopup.hbs
  src/components/Card/CardPopup.scss
  src/components/CardList/CardList.hbs
  src/components/Navbar/Navbar.hbs
  src/modules/Helpers/isEmptyDeadlineHelper.js
  src/modules/Network/Network.js
  src/modules/Router/Router.js
  src/modules/Validator/Validator.js
  src/popups/Card/CardPopUp.hbs
  src/popups/Card/CardPopUp.js
  src/popups/DeleteCard/DeleteCardPopUp.hbs
  src/popups/DeleteCard/DeleteCardPopUp.js
  src/popups/DeleteCardList/DeleteCardListPopUp.hbs
  src/stores/BoardStore/BoardStore.js
  src/stores/SettingsStore/SettingsStore.js
  src/views/BoardView/BoardView.hbs
  src/views/BoardView/BoardView.js
  src/views/BoardsView/BoardsView.js
  src/views/LoginView/LoginView.hbs
  src/views/LoginView/LoginView.js
  src/views/ProfileView/ProfileView.hbs
  src/views/ProfileView/ProfileView.js
  src/views/RegisterView/RegisterView.hbs
  src/views/RegisterView/RegisterView.js
Labels: требуется ревью менторов

#31 LDBR-2.20: Service Worker
  .eslintignore
  README.md
  package-lock.json
  package.json
  src/index.js
  src/index_template.html
  src/modules/Router/Router.js
  src/popups/BoardSetting/BoardSettingPopUp.hbs
  src/popups/CardList/CardListPopUp.hbs
  src/popups/CreateBoard/CreateBoardPopUp.hbs
  src/popups/DeleteCardList/DeleteCardListPopUp.hbs
  src/stores/BoardStore/BoardStore.js
  src/stores/UserStore/UserStore.js
  src/sw.js
  src/views/BoardsView/BoardsView.js
  src/views/ProfileView/ProfileView.js
  webpack.config.js
Labels: требуется ревью менторов

#35 LDBR 3.1: Исправить navbar, добавить аватар.
  public/assets/nodata.webp
  src/components/Navbar/Navbar.hbs
  src/components/Navbar/Navbar.js
  src/components/Navbar/Navbar.scss
  src/index.js
  src/modules/Network/Network.js
  src/modules/Router/Router.js
  src/stores/SettingsStore/SettingsStore.js
  src/stores/UserStore/UserStore.js
  src/styles/scss/Common.scss
  src/styles/scss/Constants.scss
  src/views/BoardView/BoardView.js
  src/views/BoardsView/BoardsView.js
  src/views/LoginView/LoginView.js
  src/views/NotFoundView/NotFoundView.js
  src/views/ProfileView/ProfileView.js
  src/views/RegisterView/RegisterView.js
Labels: требуется ревью менторов

#34 LDBR-3.17: Дедлайн
  src/actions/card.js
  src/components/Card/Card.hbs
  src/components/Card/Card.scss
  src/modules/Helpers/isEmptyDeadlineHelper.js
  src/modules/Validator/Validator.js
  src/popups/Card/CardPopUp.hbs
  src/popups/Card/CardPopUp.js
  src/stores/BoardStore/BoardStore.js
  src/views/BoardView/BoardView.js
Labels: требуется ревью команды

#37 LDBR 3.19: Добавление пользователей в карточку, доску, команду
  src/actions/board.js
  src/actions/boards.js
  src/actions/card.js
  src/components/BaseComponent.js
  src/components/CardList/CardList.scss
  src/components/Navbar/Navbar.hbs
  src/components/Navbar/Navbar.scss
  src/constants/constants.js
  src/modules/Network/Network.js
  src/modules/Validator/Validator.js
  src/popups/AddUser/AddUserPopUp.hbs
  src/popups/AddUser/AddUserPopUp.js
  src/popups/AddUser/AddUserPopUp.scss
  src/popups/BoardSetting/BoardSettingPopUp.scss
  src/popups/Card/CardPopUp.hbs
  src/popups/Card/CardPopUp.js
  src/popups/CreateBoard/CreateBoardPopUp.hbs
  src/popups/CreateBoard/CreateBoardPopUp.js
  src/stores/BoardStore/BoardStore.js
  src/stores/BoardsStore/BoardsStore.js
  src/stores/SettingsStore/SettingsStore.js
  src/styles/scss/Common.scss
  src/styles/scss/Constants.scss
  src/styles/scss/PopUp.scss
  src/views/BoardView/BoardView.hbs
  src/views/BoardView/BoardView.js
  src/views/BoardsView/BoardsView.hbs
  src/views/BoardsView/BoardsView.js
  src/views/BoardsView/BoardsView.scss
Labels: требуется ревью команды

#38 LDBR-3.18: Комментарии
  src/actions/comments.js
  src/modules/Helpers/IsAuthorHelper.js
  src/modules/Network/Network.js
  src/popups/Card/CardPopUp.hbs
  src/popups/Card/CardPopUp.js
  src/popups/Card/CardPopUp.scss
  src/stores/BoardStore/BoardStore.js
  src/styles/scss/Common.scss
  src/styles/scss/PopUp.scss
Labels: в работе

#36 LDBR-3.20: Правки после РК2
  src/constants/constants.js
  src/modules/Validator/Validator.js
  src/popups/BoardSetting/BoardSettingPopUp.js
  src/popups/Card/CardPopUp.js
  src/popups/CardList/CardListPopUp.js
  src/popups/CreateBoard/CreateBoardPopUp.js
  src/popups/DeleteCard/DeleteCardPopUp.hbs
  src/popups/DeleteCardList/DeleteCardListPopUp.hbs
  src/stores/UserStore/UserStore.js
  src/views/ProfileView/ProfileView.hbs
Labels: в работе

#41 LDBR-3.22: Правки после РК по интерфейсам
  src/components/Card/Card.hbs
  src/components/Card/Card.scss
  src/components/CardList/CardList.hbs
  src/constants/constants.js
  src/modules/Validator/Validator.js
  src/popups/Card/CardPopUp.hbs
  src/popups/CardList/CardListPopUp.hbs
  src/styles/scss/Common.scss
Labels: ожидает мерджа
